from __future__ import annotations


# 从真实游戏资源 `resources.assets` 中提取的 LeaderboardSO 快照。
# 若游戏版本更新，需重新从资产刷新这里。
LEADERBOARD_SNAPSHOT = {
    "lb_cactus": {
        "leaderboard_name": "cactus",
        "steam_leaderboard_name": "cactus_multi",
        "leaderboard_type": "farm_resources",
        "everything_unlocked": True,
        "single_drone": False,
        "goal_type": "item",
        "goal_resource": "Cactus",
        "goal_amount": 33_554_432,
        "start_items": (("Pumpkin", 1_000_000_000.0), ("Power", 1_000_000_000.0)),
    },
    "lb_cactus_single": {
        "leaderboard_name": "cactus_single",
        "steam_leaderboard_name": "cactus_single",
        "leaderboard_type": "farm_resources",
        "everything_unlocked": True,
        "single_drone": True,
        "goal_type": "item",
        "goal_resource": "Cactus",
        "goal_amount": 131_072,
        "start_items": (("Pumpkin", 1_000_000_000.0), ("Power", 1_000_000_000.0)),
    },
    "lb_carrots": {
        "leaderboard_name": "carrots",
        "steam_leaderboard_name": "carrots_multi",
        "leaderboard_type": "farm_resources",
        "everything_unlocked": True,
        "single_drone": False,
        "goal_type": "item",
        "goal_resource": "Carrot",
        "goal_amount": 2_000_000_000,
        "start_items": (("Power", 1_000_000_000.0), ("Hay", 1_000_000_000.0), ("Wood", 1_000_000_000.0)),
    },
    "lb_carrots_single": {
        "leaderboard_name": "carrots_single",
        "steam_leaderboard_name": "carrots_single",
        "leaderboard_type": "farm_resources",
        "everything_unlocked": True,
        "single_drone": True,
        "goal_type": "item",
        "goal_resource": "Carrot",
        "goal_amount": 100_000_000,
        "start_items": (("Power", 1_000_000_000.0), ("Hay", 1_000_000_000.0), ("Wood", 1_000_000_000.0)),
    },
    "lb_dinosaur": {
        "leaderboard_name": "dinosaur",
        "steam_leaderboard_name": "dinosaur_multi",
        "leaderboard_type": "farm_resources",
        "everything_unlocked": True,
        "single_drone": False,
        "goal_type": "item",
        "goal_resource": "Bone",
        "goal_amount": 33_488_928,
        "start_items": (("Cactus", 1_000_000_000.0), ("Power", 1_000_000_000.0)),
    },
    "lb_fastest_reset": {
        "leaderboard_name": "fastest_reset",
        "steam_leaderboard_name": "fastest_reset_multi",
        "leaderboard_type": "reset",
        "everything_unlocked": False,
        "single_drone": False,
        "goal_type": "unlock",
        "goal_resource": "Leaderboard",
        "goal_amount": 1,
        "start_items": (),
    },
    "lb_hay": {
        "leaderboard_name": "hay",
        "steam_leaderboard_name": "hay_multi",
        "leaderboard_type": "farm_resources",
        "everything_unlocked": True,
        "single_drone": False,
        "goal_type": "item",
        "goal_resource": "Hay",
        "goal_amount": 2_000_000_000,
        "start_items": (("Power", 1_000_000_000.0),),
    },
    "lb_hay_single": {
        "leaderboard_name": "hay_single",
        "steam_leaderboard_name": "hay_single",
        "leaderboard_type": "farm_resources",
        "everything_unlocked": True,
        "single_drone": True,
        "goal_type": "item",
        "goal_resource": "Hay",
        "goal_amount": 100_000_000,
        "start_items": (("Power", 1_000_000_000.0),),
    },
    "lb_maze": {
        "leaderboard_name": "maze",
        "steam_leaderboard_name": "maze_multi",
        "leaderboard_type": "farm_resources",
        "everything_unlocked": True,
        "single_drone": False,
        "goal_type": "item",
        "goal_resource": "Gold",
        "goal_amount": 9_863_168,
        "start_items": (("Weird_Substance", 1_000_000_000.0), ("Power", 1_000_000_000.0)),
    },
    "lb_maze_single": {
        "leaderboard_name": "maze_single",
        "steam_leaderboard_name": "maze_single",
        "leaderboard_type": "farm_resources",
        "everything_unlocked": True,
        "single_drone": True,
        "goal_type": "item",
        "goal_resource": "Gold",
        "goal_amount": 616_448,
        "start_items": (("Weird_Substance", 1_000_000_000.0), ("Power", 1_000_000_000.0)),
    },
    "lb_pumpkins": {
        "leaderboard_name": "pumpkins",
        "steam_leaderboard_name": "pumpkins_multi",
        "leaderboard_type": "farm_resources",
        "everything_unlocked": True,
        "single_drone": False,
        "goal_type": "item",
        "goal_resource": "Pumpkin",
        "goal_amount": 200_000_000,
        "start_items": (("Carrot", 1_000_000_000.0), ("Power", 1_000_000_000.0)),
    },
    "lb_pumpkins_single": {
        "leaderboard_name": "pumpkins_single",
        "steam_leaderboard_name": "pumpkins_single",
        "leaderboard_type": "farm_resources",
        "everything_unlocked": True,
        "single_drone": True,
        "goal_type": "item",
        "goal_resource": "Pumpkin",
        "goal_amount": 10_000_000,
        "start_items": (("Carrot", 1_000_000_000.0), ("Power", 1_000_000_000.0)),
    },
    "lb_sunflowers": {
        "leaderboard_name": "sunflowers",
        "steam_leaderboard_name": "sunflowers_multi",
        "leaderboard_type": "farm_resources",
        "everything_unlocked": True,
        "single_drone": False,
        "goal_type": "item",
        "goal_resource": "Power",
        "goal_amount": 100_000,
        "start_items": (("Carrot", 1_000_000_000.0),),
    },
    "lb_sunflowers_single": {
        "leaderboard_name": "sunflowers_single",
        "steam_leaderboard_name": "sunflowers_single",
        "leaderboard_type": "farm_resources",
        "everything_unlocked": True,
        "single_drone": True,
        "goal_type": "item",
        "goal_resource": "Power",
        "goal_amount": 10_000,
        "start_items": (("Carrot", 1_000_000_000.0),),
    },
    "lb_wood": {
        "leaderboard_name": "wood",
        "steam_leaderboard_name": "wood_multi",
        "leaderboard_type": "farm_resources",
        "everything_unlocked": True,
        "single_drone": False,
        "goal_type": "item",
        "goal_resource": "Wood",
        "goal_amount": 10_000_000_000,
        "start_items": (("Power", 1_000_000_000.0),),
    },
    "lb_wood_single": {
        "leaderboard_name": "wood_single",
        "steam_leaderboard_name": "wood_single",
        "leaderboard_type": "farm_resources",
        "everything_unlocked": True,
        "single_drone": True,
        "goal_type": "item",
        "goal_resource": "Wood",
        "goal_amount": 500_000_000,
        "start_items": (("Power", 1_000_000_000.0),),
    },
}
