from __future__ import annotations


# 当前默认 unlock 快照。若用户刷新真实存档快照，再按需更新这里。
DEFAULT_UNLOCK_LEVELS = {
    "Auto_Unlock": 1,
    "Cactus": 6,
    "Carrots": 10,
    "Costs": 1,
    "Debug": 1,
    "Debug_2": 1,
    "Dictionaries": 1,
    "Dinosaurs": 6,
    "Expand": 9,
    "Fertilizer": 4,
    "Functions": 1,
    "Grass": 10,
    "Hats": 1,
    "Import": 1,
    "Leaderboard": 1,
    "Lists": 1,
    "Loops": 1,
    "Mazes": 6,
    "Megafarm": 5,
    "Operators": 1,
    "Plant": 1,
    "Polyculture": 5,
    "Pumpkins": 10,
    "Senses": 1,
    "Simulation": 1,
    "Speed": 5,
    "Sunflowers": 1,
    "The_Farmers_Remains": 1,
    "Timing": 1,
    "Top_Hat": 1,
    "Trees": 10,
    "Utilities": 1,
    "Variables": 1,
    "Watering": 9,
}
