from __future__ import annotations

from enum import Enum


class TokenType(Enum):
    NO_TOKEN = "NO_TOKEN"
    IGNORE = "IGNORE"
    NUM = "NUM"
    IDENTIFIER = "IDENTIFIER"
    STRING = "STRING"
    DEF = "DEF"
    BRACKET_OPEN = "BRACKET_OPEN"
    BRACKET_CLOSE = "BRACKET_CLOSE"
    SQUARE_BRACKET_OPEN = "SQUARE_BRACKET_OPEN"
    SQUARE_BRACKET_CLOSE = "SQUARE_BRACKET_CLOSE"
    CURL_BRACE_OPEN = "CURL_BRACE_OPEN"
    CURL_BRACE_CLOSE = "CURL_BRACE_CLOSE"
    COMMA = "COMMA"
    COLON = "COLON"
    DOT = "DOT"
    NEW_LINE = "NEW_LINE"
    ASSIGN = "ASSIGN"
    IF = "IF"
    ELSE = "ELSE"
    ELIF = "ELIF"
    FOR = "FOR"
    IN = "IN"
    WHILE = "WHILE"
    OR = "OR"
    AND = "AND"
    NOT = "NOT"
    COMPARE = "COMPARE"
    ADD = "ADD"
    MULT = "MULT"
    EXP = "EXP"
    ARROW = "ARROW"
    UNION = "UNION"
    PASS = "PASS"
    RETURN = "RETURN"
    BREAK = "BREAK"
    CONTINUE = "CONTINUE"
    GLOBAL = "GLOBAL"
    IMPORT = "IMPORT"
    FROM = "FROM"
    UNKNOWN = "UNKNOWN"
